const express = require("express");
const getAllAppointment = require("../controller/getAllAppointment");
const getAllUsers = require("../controller/getAllUsers");
const { route } = require("./LoginRoute");
const createNewCourse = require("../controller/createNewCourse");
const getAllCourses = require("../controller/getAllCourses");
const addSevFivVideo = require("../controller/addSevFivVideo");
const getSevFivVideos = require("../controller/getSevFivVideos");
const editSevFivVideo = require("../controller/editSevFivVideo");
const deleteSevFivVideo = require("../controller/deleteSevFivVideo");
const AddCourseVideo = require("../controller/AddCourseVideo");
const getAllCourseVideo = require("../controller/getAllCourseVideo");
const editCourseVideo = require("../controller/editCourseVideo");
const deleteCourseVideo = require("../controller/deleteCourseVideo");
const addPrevVideo = require("../controller/addPrevVideo");
const getPrevVideo = require("../controller/getPrevVideo");
const updatePrevVideo = require("../controller/updatePrevVideo");
const deletePrevVideo = require("../controller/deletePrevVideo");
const addUpcomingTraining = require("../controller/addUpcomingTraining");
const getUpcoming = require("../controller/getUpcoming");
const deleteUpcomin = require("../controller/deleteUpcomin");
const addSocialMediaContent = require("../controller/addSocialMediaContent");
const getAllSocialContent = require("../controller/getAllSocialContent");
const updateSocialMedia = require("../controller/updateSocialMedia");
const deleteSocialMedia = require("../controller/deleteSocialMedia");
const addExploreMore = require("../controller/addExploreMore");
const getExploreMore = require("../controller/getExploreMore");
const updateExploreMore = require("../controller/updateExploreMore");
const deleteExploreMore = require("../controller/deleteExploreMore");
const router = express.Router();

router.get("/getAllUser", getAllUsers);
router.get("/getallappointments", getAllAppointment);
router.get("/getAllCourses", getAllCourses);
router.get("/getVideos", getSevFivVideos);
router.get("/getCourseVideos", getAllCourseVideo);
router.get("/getprevvideo", getPrevVideo);
router.get("/getupcomingtrainings", getUpcoming);
router.get("/get-social-media", getAllSocialContent);
router.get("/explore-more", getExploreMore);
router.put("/social-media/:id", updateSocialMedia);
router.put("/updateCourseVideo/:id", editCourseVideo);
router.put("/updateVideo/:id", editSevFivVideo);
router.post("/explore-more", addExploreMore);
router.post("/social-media", addSocialMediaContent);
router.post("/addCourseVideo", AddCourseVideo);
router.post("/createCourse", createNewCourse);
router.post("/addVideo", addSevFivVideo);
router.post("/addprevvideo", addPrevVideo);
router.post("/setupcomingtraining", addUpcomingTraining);
router.put("/updateprevvideo/:id", updatePrevVideo);
router.put("/explore-more/:id", updateExploreMore);
router.delete("/social-media/:id", deleteSocialMedia);
router.delete("/deleteVideo/:id", deleteSevFivVideo);
router.delete("/deleteCourseVideo/:id", deleteCourseVideo);
router.delete("/deleteprevvideo/:id", deletePrevVideo);
router.delete("/deleteupcomingtraining/:id", deleteUpcomin);
router.delete("/explore-more/:id", deleteExploreMore);

module.exports = router;
